### ISSUE TITLE
omg

### ISSUE THREAD

**Issue by xuziangh** [VeibaeMCC/VeibaeClient#2]
Veibae姐姐，问个问题，以后的veibae client是不是只提供client,不提供源码

**Comment by xuziangh** [comment]
还有，你以后打算是先加强功能呢，还是先弄视觉

**Comment by VeibaeMCC** [comment]
> Veibae姐姐，问个问题，以后的veibae client是不是只提供client,不提供源码

嗯

**Comment by VeibaeMCC** [comment]
> Veibae姐姐，问个问题，以后的veibae client是不是只提供client,不提供源码

前期源码加入保密计划，后期大概率会开源

**Comment by VeibaeMCC** [comment]
> 还有，你以后打算是先加强功能呢，还是先弄视觉

视觉，功能目前不需要大更新，UI设计语言打算用facebook或者google的，功能不打算用kotlin，可能兼容go语言和java混用
