### ISSUE TITLE
FUCK U VERIBAE

### ISSUE THREAD

**Issue by harryvision** [VeibaeMCC/VeibaeClient#3]
FUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK UFUCK U

**Comment by VeibaeMCC** [comment]
我已经把你从我的库ban了，再见
